name: Checkout
on: [push]

jobs:
  checkout-actiop:
    runs-on: ubuntu-latest
    steps:
      - name: List files before checkout
        run: ls -a
      - uses: actions/checkout@v4
      - name: List files after
        run: ls -a    
  